---
sudo: required
matrix:
  include:

    - env: TARGET="x86_64-unknown-linux"
      os: linux
      language: python

    - env: TARGET="x86_64-apple-darwin"
      os: osx
      language: c

  allow_failures:
    - env: TARGET="x86_64-apple-darwin"

cache:
  directories:
    - /usr/local/lib/ats2-postiats-0.3.8/
    - /usr/local/bin

install:
  - wget http://ats-lang.sourceforge.net/IMPLEMENT/Postiats/ATS2-Postiats-0.3.8.tgz
  - tar xvf ATS2-Postiats-0.3.8.tgz
  - cd ATS2-Postiats-0.3.8 && ./configure && make && sudo make install
  - cd ../
  - rm -rf ATS2-Postiats-0.3.8

# FIXME: use shellcheck -e 2155 with 'nix-env -i ShellCheck'?
script:
  - |
    if [ $TARGET = "x86_64-unknown-linux" ]
    then
      pip install yamllint
      yamllint .travis.yml
      curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s shake.hs
      curl -sL https://raw.githubusercontent.com/vmchale/tomlcheck/master/sh/check | sh -s .atsfmt.toml
    else
      echo "skipping..."
    fi
  - export COMMAND="gcc -flto -I/usr/local/lib/ats2-postiats-0.3.8/ccomp/runtime/ -I/usr/local/lib/ats2-postiats-0.3.8/"
  - |
    if [ $TARGET = "x86_64-unknown-linux" ]
    then
      patscc -atsccomp "$COMMAND" src/polyglot.dats -DATS_MEMALLOC_LIBC -o poly-$TARGET -cleanaft -O2 -flto -lpthread
    else
      patscc -atsccomp "$COMMAND" src/compat.dats -DATS_MEMALLOC_LIBC -o poly-$TARGET -cleanaft -O2 -flto
    fi

deploy:
  api_key:
    secure: "A7A2h7iYFO8z+wK3He9W2Y18G5leAlPhAtL2/HtJsAL/rIog+K5MB1rn7lcSWFgXMimMA+aWmr5PQHPLstVqt6IZNv3O/LV4We95Yr5HhHH+QP76zDChzRTM++9eRX/AIAJB4mZgyguZXXYdco6m/4Wj5DO/I2gyniP3sajqOsEhCnASskhcCoQhp9XGWSiRgowWxiKvjfLDAR6Bt/B9lLfg+gTR9VTQGrbAbSzwEWb7qlRp9P5WHNzWaof7C+6NM7XP+OMwENEJ/5KKNXiHEbht0GpU6Mmga7PpB8W2NzsKoFaG2nOmp+iyzp9sl+oC0pBycxX7n2+unDoW04kJPTLYNBW+xN/yj7c0Ioujnq4XXJWCckpwg4pK7/zj6FeQJULAHplCEZf5HxCBPZ1TnvsfpdqeYD1Vjf/B0DzVnvhrPDasG0Et1iFedBvc9YL7fkyypc45ySXbnRlupr5KknMGqIUrC0QiY0jP9+LGTfWu4IoN3ArUItcfs/D99w6PH82FU9Z+AkDEWHaVtPwXN9y43Pt1p7vuIszCYY3/So1TrFtmPwsYnjVIiKrhQIzx2N5tN9pyZiiQBY1QU5/k6kEXIdXXScGIJbT1qqcTqMduguguS6NDygiJ9nomFnUS0wPMpLKP5T31aAble6rWuHTlM0tyZ4l3qJbNSWPDUPw="
  file: poly-$TARGET
  on:
    tags: true
  provider: releases
  skip_cleanup: true
