---
language: python
os:
  - linux
  - osx

cache:
  - $HOME/libats

before_install:
  - git clone git://git.code.sf.net/p/ats2-lang/code ATS2-Postiats
  - cd ATS2-Postiats && ./configure --prefix $HOME/libats && make && make install

script:
  - export PATSHOME=$HOME/libats
  - export PATH=$PATSHOME/bin:$PATH
  - patscc src/polyglot.dats -DATS_MEMALLOC_LIBC -o poly -cleanaft -O2 -flto
